name: Deploy

on:
  workflow_dispatch:
    inputs:
      label:
        default: main
        type: string
        required: true
        description: docker image label to deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CI_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Sync Compose
        run: |
          rsync -aze 'ssh -p ${{ secrets.CI_PORT }}' ${{ github.workspace }}/deploy-compose.yml ci@${{ secrets.CI_HOST }}:/home/ci/houston/
          ssh -p ${{ secrets.CI_PORT }} ci@${{ secrets.CI_HOST }} <<HOUSTON
            mkdir -p ~/houston
            cd ~/houston
            echo ${{ secrets.PAT }} | docker login ghcr.io -u GalacticraftDev --password-stdin
            IMAGE_TAG=${{ inputs.label }}
            BIND_HOST=${{ secrets.BIND_HOST }}
            BIND_PORT=${{ secrets.BIND_PORT }}
            UI_URL=https://capes.galacticraft.team
            POSTGRES_PASSWORD=${{ secrets.PG_PASS }}
            MSA_ID=${{ secrets.MSA_ID }}
            MSA_SECRET=${{ secrets.MSA_SECRET }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            docker pull ghcr.io/teamgalacticraft/houston:${IMAGE_TAG}
            docker-compose -f deploy-compose.yml up -d
          HOUSTON
