name: Build Rust

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        id: build-cache
        uses: actions/cache@v3
        with:
          path: target/**
          key: ${{ runner.os }}-build-cache
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        env:
          SQLX_OFFLINE: true
      - name: Build Houston
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          SQLX_OFFLINE: true